name: pyviz37test
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
 - attrs==19.3.0
 - backcall==0.1.0
 - bleach==3.1.1
 - bokeh==1.4.0
 - branca==0.4.0
 - Cartopy==0.17.0
 - certifi==2019.11.28
 - cffi==1.14.0
 - cftime==1.0.4.2
 - chardet==3.0.4
 - Click==7.0
 - click-plugins==1.1.1
 - cligj==0.5.0
 - cloudpickle==1.3.0
 - colorama==0.4.3
 - colorcet==2.0.1
 - cryptography==2.8
 - cycler==0.10.0
 - cytoolz==0.10.1
 - dask==2.12.0
 - datashader==0.10.0
 - datashape==0.5.4
 - decorator==4.4.1
 - defusedxml==0.6.0
 - descartes==1.1.0
 - distributed==2.12.0
 - entrypoints==0.3
 - Fiona==1.8.4
 - folium==0.10.1
 - fsspec==0.6.2
 - GDAL==2.3.3
 - geographiclib==1.50
 - geopandas==0.6.1
 - geopy==1.21.0
 - geoviews==1.6.6
 - HeapDict==1.0.1
 - holoviews==1.12.7
 - idna==2.9
 - imageio==2.8.0
 - importlib-metadata==1.5.0
 - ipykernel==5.1.4
 - ipython==7.12.0
 - ipython_genutils=0.2.0=py37_0
 - ipywidgets==7.5.1
 - jedi==0.16.0
 - Jinja2==2.11.1
 - joblib==0.14.1
 - jsonschema==3.2.0
 - jupyter_client=5.3.4=py37_0
 - jupyter_console=6.1.0=py_0
 - jupyter-core==4.6.1
 - kiwisolver==1.1.0
 - llvmlite==0.31.0
 - locket==0.2.0
 - Markdown==3.2.1
 - MarkupSafe==1.1.1
 - matplotlib==3.2.0
 - mistune==0.8.4
 - mkl-service==2.3.0
 - msgpack==1.0.0
 - multipledispatch==0.6.0
 - munch==2.5.0
 - nbconvert==5.6.1
 - nbformat==5.0.4
 - netCDF4==1.4.2
 - networkx==2.4
 - notebook==6.0.3
 - numba==0.48.0
 - numpy==1.18.1
 - olefile==0.46
 - osmnx==0.11.3
 - OWSLib==0.19.1
 - packaging==20.1
 - pandas==1.0.1
 - pandocfilters==1.4.2
 - panel==0.8.0
 - param==1.9.3
 - parso==0.6.1
 - partd==1.1.0
 - patsy==0.5.1
 - pickleshare==0.7.5
 - Pillow==7.0.0
 - prometheus-client==0.7.1
 - prompt_toolkit=3.0.3=py_0
 - psutil==5.7.0
 - pycparser==2.20
 - pyct==0.4.6
 - pyepsg==0.4.0
 - Pygments==2.5.2
 - pykdtree==1.3.1
 - pyOpenSSL==19.1.0
 - pyparsing==2.4.6
 - pyproj==1.9.6
 - pyrsistent==0.14.11
 - pyshp==2.1.0
 - PySocks==1.7.1
 - python-dateutil==2.8.1
 - pytz==2019.3
 - pyviz_comms=0.7.3=py_0
 - PyWavelets==1.1.1
 - pywin32==227
 - pywinpty=0.5.7=py37_0
 - PyYAML==5.3
 - pyzmq==18.1.1
 - qtconsole==4.7.1
 - QtPy==1.9.0
 - requests==2.23.0
 - Rtree==0.9.4
 - scikit-image==0.16.2
 - scikit-learn==0.22.2.post1
 - scipy==1.4.1
 - seaborn==0.10.0
 - Send2Trash==1.5.0
 - Shapely==1.6.4.post1
 - six==1.14.0
 - sortedcontainers==2.1.0
 - statsmodels==0.11.1
 - tblib==1.6.0
 - terminado==0.8.3
 - testpath==0.4.4
 - toolz==0.10.0
 - tornado==6.0.3
 - tqdm==4.43.0
 - traitlets==4.3.3
 - urllib3==1.25.7
 - vincent==0.4.4
 - wcwidth==0.1.8
 - webencodings==0.5.1
 - widgetsnbextension==3.5.1
 - win-inet-pton==1.1.0
 - wincertstore==0.2
 - xarray==0.15.0
 - zict==2.0.0
 - zipp==3.1.0
